HF2Comp <- function(model,
                    halfLifeHours_A,
                    halfLifeHours_B,
                    Vcentral,
                    Vcartridge,
                    initial_concentration_A,
                    initial_concentration_B,
                    lastTimePointHours,
                    Vinject_ABolus,
                    Vinject_B_centralBolus,
                    Vinject_B_extraBolus,
                    dosingIntervalHours_ABolus,
                    dosingIntervalHours_BBolus,
                    numberOfDosesABolus,
                    numberOfDosesBBolus,
                    drugNameA,
                    drugNameB,
                    adm.type,
                    tinfuseHours_A,
                    tinfuseHours_B,
                    Vinject_AInf,
                    Vinject_B_centralInf,
                    Vinject_B_extraInf,
                    dosingIntervalHours_AInf,
                    dosingIntervalHours_BInf,
                    numberOfDosesAInf,
                    numberOfDosesBInf,
                    constantVolume = T,
                    debit_central_cartridge = 120)
{
  Parameters <- HollowFibre2CompParam(
    halfLifeHours_A,
    halfLifeHours_B,
    Vcentral,
    Vcartridge,
    initial_concentration_A,
    initial_concentration_B,
    lastTimePointHours,
    Vinject_ABolus,
    Vinject_B_centralBolus,
    Vinject_B_extraBolus,
    dosingIntervalHours_ABolus,
    dosingIntervalHours_BBolus,
    numberOfDosesABolus,
    numberOfDosesBBolus,
    drugNameA,
    drugNameB,
    adm.type,
    tinfuseHours_A,
    tinfuseHours_B,
    Vinject_AInf,
    Vinject_B_centralInf,
    Vinject_B_extraInf,
    dosingIntervalHours_AInf,
    dosingIntervalHours_BInf,
    numberOfDosesAInf,
    numberOfDosesBInf
  )

  SimData <- HollowFibre2CompSimData(
    model,
    halfLifeHours_A,
    halfLifeHours_B,
    Vcentral,
    Vcartridge,
    initial_concentration_A,
    initial_concentration_B,
    lastTimePointHours,
    Vinject_ABolus,
    Vinject_B_centralBolus,
    Vinject_B_extraBolus,
    dosingIntervalHours_ABolus,
    dosingIntervalHours_BBolus,
    numberOfDosesABolus,
    numberOfDosesBBolus,
    drugNameA,
    drugNameB,
    adm.type,
    tinfuseHours_A,
    tinfuseHours_B,
    Vinject_AInf,
    Vinject_B_centralInf,
    Vinject_B_extraInf,
    dosingIntervalHours_AInf,
    dosingIntervalHours_BInf,
    numberOfDosesAInf,
    numberOfDosesBInf,
    constantVolume = T,
    debit_central_cartridge
  )

  Plot <- HollowFibre2CompPlot(SimData,
                               lastTimePointHours,
                               drugNameA,
                               drugNameB,
                               adm.type)

  Diagram <- HollowFibre2CompDiagram(Parameters,
                                     adm.type)


  return(list(Parameters, Plot, Diagram, SimData))
}
