---
title: "Development of input modules"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

Document the creation of Shiny modules for input. Each module consists of ui for user inputs and the server logic that 
enables the storage of user inputs.

# input_pump_ui

```{r function-input_pump_ui}
#' input_pump_ui Ui elements for the user to input pump characteristics
#'
#' @return tagList of ui elements
#' @export
#'
#' @examples
input_modules <- function(id) {
  # This ns <- NS structure creates a
  # "namespacing" function, that will
  # prefix all ids with a string
  ns <- NS(ID)
  tagList(
    box(
      title = "Pump characteristics",
      status = "primary",
      solidHeader = TRUE,
      collapsible = TRUE,
      width = 3,
      numericInput(
        ns("minPumpFlow"),
        "Minimum Pump Flow (mL/min)",
        0.4,
        min = 0,
        step = 0.1
      ),
      numericInput(
        ns("maxPumpFlow"),
        "Maximum Pump Flow (mL/min)",
        150,
        min = 0,
        step = 0.1
      ),
      numericInput(
        ns("stepPumpFlow"),
        "Step of pump (mL/min)",
        0.1,
        min = 0,
        step = 0.1
      )
    )
  )
}
```

```{r examples-input_pump_ui}
input_pump_ui("1comp")
```

```{r tests-input_pump_ui}
test_that("input_pump_ui works", {

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_input_modules.Rmd", vignette_name = "Go further")
```

